<?php

return [
    'default_country' => 'IN',

    'definitions' => [
        'cash' => [
            'label' => 'Cash on Delivery',
            'channel' => 'manual',
            'sort' => 10,
            'countries' => ['*'],
            'enabled' => true,
            'description' => 'Manual collection at checkout, counter, or delivery handoff.',
            'fields' => [],
        ],
        'stripe' => [
            'label' => 'Stripe',
            'channel' => 'card',
            'sort' => 20,
            'countries' => ['*'],
            'enabled' => false,
            'description' => 'Card payments for international checkout flows.',
            'fields' => [
                ['key' => 'publishable_key', 'label' => 'Publishable Key', 'type' => 'text', 'placeholder' => 'pk_live_...'],
                ['key' => 'secret_key', 'label' => 'Secret Key', 'type' => 'password', 'placeholder' => 'sk_live_...'],
                ['key' => 'webhook_secret', 'label' => 'Webhook Secret', 'type' => 'password', 'placeholder' => 'whsec_...'],
            ],
        ],
        'paypal' => [
            'label' => 'PayPal',
            'channel' => 'online',
            'sort' => 30,
            'countries' => ['*'],
            'enabled' => false,
            'description' => 'Global wallet and card payments through PayPal.',
            'fields' => [
                ['key' => 'client_id', 'label' => 'Client ID', 'type' => 'text', 'placeholder' => 'Client ID'],
                ['key' => 'client_secret', 'label' => 'Client Secret', 'type' => 'password', 'placeholder' => 'Client Secret'],
                ['key' => 'mode', 'label' => 'Mode', 'type' => 'text', 'placeholder' => 'sandbox or live'],
                ['key' => 'webhook_id', 'label' => 'Webhook ID', 'type' => 'text', 'placeholder' => 'PayPal webhook id'],
            ],
        ],
        'razorpay' => [
            'label' => 'Razorpay',
            'channel' => 'online',
            'sort' => 40,
            'countries' => ['IN'],
            'enabled' => false,
            'description' => 'India-focused cards, UPI, wallets, and netbanking.',
            'fields' => [
                ['key' => 'key_id', 'label' => 'Key ID', 'type' => 'text', 'placeholder' => 'rzp_live_...'],
                ['key' => 'key_secret', 'label' => 'Key Secret', 'type' => 'password', 'placeholder' => 'Key Secret'],
                ['key' => 'webhook_secret', 'label' => 'Webhook Secret', 'type' => 'password', 'placeholder' => 'Webhook Secret'],
            ],
        ],
        'paytm' => [
            'label' => 'Paytm',
            'channel' => 'upi',
            'sort' => 50,
            'countries' => ['IN'],
            'enabled' => false,
            'description' => 'UPI and wallet flows for India checkout.',
            'fields' => [
                ['key' => 'upi_vpa', 'label' => 'UPI VPA', 'type' => 'text', 'placeholder' => 'merchant@upi'],
                ['key' => 'merchant_name', 'label' => 'Merchant Name', 'type' => 'text', 'placeholder' => 'Merchant Name'],
                ['key' => 'note_prefix', 'label' => 'Note Prefix', 'type' => 'text', 'placeholder' => 'Order'],
                ['key' => 'merchant_id', 'label' => 'Merchant ID', 'type' => 'text', 'placeholder' => 'Merchant ID'],
                ['key' => 'merchant_key', 'label' => 'Merchant Key', 'type' => 'password', 'placeholder' => 'Merchant Key'],
                ['key' => 'website', 'label' => 'Website', 'type' => 'text', 'placeholder' => 'WEBSTAGING or DEFAULT'],
                ['key' => 'industry_type', 'label' => 'Industry Type', 'type' => 'text', 'placeholder' => 'Retail'],
            ],
        ],
        'phonepe' => [
            'label' => 'PhonePe',
            'channel' => 'upi',
            'sort' => 60,
            'countries' => ['IN'],
            'enabled' => false,
            'description' => 'PhonePe UPI and collect requests for India.',
            'fields' => [
                ['key' => 'upi_vpa', 'label' => 'UPI VPA', 'type' => 'text', 'placeholder' => 'merchant@upi'],
                ['key' => 'merchant_name', 'label' => 'Merchant Name', 'type' => 'text', 'placeholder' => 'Merchant Name'],
                ['key' => 'note_prefix', 'label' => 'Note Prefix', 'type' => 'text', 'placeholder' => 'Order'],
                ['key' => 'merchant_id', 'label' => 'Merchant ID', 'type' => 'text', 'placeholder' => 'Merchant ID'],
                ['key' => 'salt_key', 'label' => 'Salt Key', 'type' => 'password', 'placeholder' => 'Salt Key'],
                ['key' => 'salt_index', 'label' => 'Salt Index', 'type' => 'text', 'placeholder' => '1'],
            ],
        ],
        'gpay' => [
            'label' => 'Google Pay',
            'channel' => 'upi',
            'sort' => 70,
            'countries' => ['IN'],
            'enabled' => false,
            'description' => 'Google Pay UPI intent support for India customers.',
            'fields' => [
                ['key' => 'upi_vpa', 'label' => 'UPI VPA', 'type' => 'text', 'placeholder' => 'merchant@upi'],
                ['key' => 'merchant_name', 'label' => 'Merchant Name', 'type' => 'text', 'placeholder' => 'Merchant Name'],
                ['key' => 'note_prefix', 'label' => 'Note Prefix', 'type' => 'text', 'placeholder' => 'Order'],
            ],
        ],
        'upi' => [
            'label' => 'UPI',
            'channel' => 'upi',
            'sort' => 80,
            'countries' => ['IN'],
            'enabled' => false,
            'description' => 'Generic UPI intent / QR checkout for India.',
            'fields' => [
                ['key' => 'upi_vpa', 'label' => 'UPI VPA', 'type' => 'text', 'placeholder' => 'merchant@upi'],
                ['key' => 'merchant_name', 'label' => 'Merchant Name', 'type' => 'text', 'placeholder' => 'Merchant Name'],
                ['key' => 'note_prefix', 'label' => 'Note Prefix', 'type' => 'text', 'placeholder' => 'Order'],
            ],
        ],
    ],
];
